spring:
  application:
    name: aircraft

  datasource:
    url: jdbc:postgresql://localhost:5435/Aircraft
    driver-class-name: org.postgresql.Driver
    username: aircraft_dev
    password: aircraft_dev12
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true
    locations: classpath:db/migration


server:
  port: 8080